# configuration for alignment pipeline
reference: /proj/ideel/meshnick/users/NickB/Projects/jiffy_salmonella/GCF_000006945.2_ASM694v2_genomic.fna

adapters: /nas02/apps/trimmomatic-0.36/Trimmomatic-0.36/adapters/TruSeq3-PE.fa
min_trimmed_length: 30

logs: jobs
tmpdir: .tmp
readbuffer: 1000000
threads: 6
memory: 12

runs: salmonella_run_map.tab.txt
aligned: aln
fastq: fastq
