# configuration for alignment pipeline
reference: /proj/ideel/meshnick/users/NickB/Projects/jiffy_salmonella/refgenomes/GCF_000006945.2_ASM694v2_genomic.fna

adapters: /nas02/apps/trimmomatic-0.36/Trimmomatic-0.36/adapters/TruSeq3-PE.fa
min_trimmed_length: 30

logs: jobs
tmpdir: .tmp
readbuffer: 1000000
threads: 6
memory: 12

runs: /proj/ideel/meshnick/users/NickB/Projects/jiffy_salmonella/snake_align/salmonella_run_map.tab.txt
aligned: /pine/scr/n/f/nfb/Projects/jiffy_salmonella/snake_align/aln/
fastq: /proj/ideel/meshnick/users/NickB/Projects/jiffy_salmonella/snake_align/fastq/
