accessions: /proj/ideel/meshnick/users/NickB/Projects/jiffy_salmonella/snakescrape/ENA_master_acc_download_map.tab.txt
scratch: /pine/scr/n/f/nfb/Projects/jiffy_salmonella/public_seqs/logs/
outputdir: /pine/scr/n/f/nfb/Projects/jiffy_salmonella/public_seqs/
