## Connectivity by Geography - Edge Density
---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(tidygraph)
library(ggraph)
library(cowplot)
```

```{r}
# convert to network
ibD.meiotic.network <- ibD.meiotic %>% 
  tidygraph::as_tbl_graph(., directed = F) %>% 
  tidygraph::activate("nodes") %>% 
  dplyr::left_join(., mtdt, by = "name")

# edges
meiotic.edges <- ibD.meiotic.network %>% 
  tidygraph::activate("edges") %>% 
  tibble::as_tibble()


# nodes that only have one connection
meiotic_clst.uni <- ibD.meiotic.network %>% 
  tidygraph::activate("nodes") %>%
  dplyr::mutate(node_edge_density = igraph::degree(.)) %>%
  dplyr::filter(c(node_edge_density == 1 | 
                    name %in% c("3002B1W5E", "Z2H3M")# catch violation of transitivity 
  ) 
  )

meiotic_clst.uni.plotobj <- meiotic_clst.uni %>% 
  ggraph(layout = "kk") +
  #geom_node_point(aes(shape = factor(hv001), fill = factor(hv001)), show.legend = F) +
  geom_edge_link(aes(color  = malecotf), width = 1.2, alpha = 0.5) +
  scale_edge_color_viridis("Pairwise IBD") +
  scale_shape_manual(values = rep(c(21, 22, 23, 24, 25), 12)) +
  geom_node_text(aes(label = hv001)) +
  theme_graph() +
  theme(legend.position = "right",
        legend.title = element_text(family = "Helvetica", vjust = 0.85, hjust = 0.5, size = 13, face = "bold"),
        legend.text = element_text(family = "Helvetica", hjust = 1, size = 11, face = "bold"))

# nodes with multiple connections
meiotic_clst.conn <- ibD.meiotic.network %>% 
  tidygraph::activate("nodes") %>% 
  dplyr::mutate(node_edge_density = igraph::degree(.)) %>% 
  dplyr::filter(node_edge_density > 1) 

meiotic_clst.conn.PlotObj <- meiotic_clst.conn %>% 
  ggraph(layout = "kk") +
  #geom_node_point(aes(shape = factor(hv001), fill = factor(hv001)), show.legend = F) +
  geom_edge_link(aes(color  = malecotf), width = 1.2, alpha = 0.5) +
  scale_edge_color_viridis("Pairwise IBD") +
  scale_shape_manual(values = rep(c(21, 22, 23, 24, 25), 12)) +
  geom_node_text(aes(label = hv001)) +
  theme_graph() +
  theme(legend.position = "right",
        legend.title = element_text(family = "Helvetica", vjust = 0.85, hjust = 0.5, size = 13, face = "bold"),
        legend.text = element_text(family = "Helvetica", hjust = 1, size = 11, face = "bold"))

#...................... 
# lay this out for potential figure
#......................
meiotic_sib_networkplot <- cowplot::plot_grid(
  meiotic_clst.uni.plotobj + theme(legend.position = "none"),
  meiotic_clst.conn.PlotObj + theme(legend.position = "none"),
  labels = c("(B)", "(C)"),
  align = "v", ncol = 1)


legend <- cowplot::get_legend(meiotic_clst.uni.plotobj +  
                                theme(legend.position = "bottom",
                                      legend.text = element_text(family = "Helvetica", size = 11, face = "bold", angle = 45)) +
                                guides(color = guide_legend(nrow = 1)))

meiotic_sib_networkplot <- cowplot::plot_grid(meiotic_sib_networkplot, legend, ncol = 1, rel_heights = c(1, 0.1))


#............................................................
# Now pull in and look at Edge Density by geography
#...........................................................
EdgeDens <- ibD.meiotic.network %>% 
  tidygraph::activate(., "nodes") %>% 
  dplyr::mutate(node_edge_density = igraph::degree(.)) %>%
  tibble::as_tibble(.) 

# node labels
nodelabels <- EdgeDens %>% 
  dplyr::select(c("longnum", "latnum", "hv001")) %>% 
  dplyr::filter(!duplicated(.))

# edge plot
edge_dens_plot <- EdgeDens %>% 
  dplyr::mutate(node_edge_density_disc = factor(node_edge_density, # this is a count, so discreteize
                                                levels = 1:max(EdgeDens$node_edge_density))) %>% 
  ggplot() +
  geom_sf(data = DRCprov, color = "#737373", fill = "#525252", size = 0.05) +
  smpl_base_map +
  geom_point(aes(x = longnum, y = latnum, 
                 fill = node_edge_density_disc), 
             alpha = 0.5, size = 2, shape = 21, stroke = 0.3, color = "#d9d9d9") +
  ggrepel::geom_text_repel(data = nodelabels,
                           aes(x = longnum, y = latnum, label = hv001), 
                           size = 3, fontface = "bold", color = "#bdbdbd") +
  scale_fill_manual("Edge Density", values = rev(RColorBrewer::brewer.pal(max(EdgeDens$node_edge_density), 
                                                                          name = "RdYlBu"))) +
  theme(legend.position = "bottom",
        legend.text = element_text(angle = 0))


```


```{r, results='asis'}
cowplot::plot_grid(edge_dens_plot, meiotic_sib_networkplot, 
                   ncol = 2, rel_widths = c(1, 0.75),
                   labels = c("(A)", ""))

# potential manuscript figure
jpeg("results/figures/meiotic_sib_network_num_geo_connections.jpg", width = 11, height = 8, units = "in", res = 800)
cowplot::plot_grid(edge_dens_plot, meiotic_sib_networkplot, 
                   ncol = 2, rel_widths = c(1, 0.75),
                   labels = c("(A)", ""))
graphics.off()

```
Overall, there are `r nrow(meiotic.edges)` highly-related pairs. Among these highly related pairs, `r sum(meiotic.edges$hv001.x == meiotic.edges$hv001.y)` were from the same cluster. There are `r sum(EdgeDens$node_edge_density == 1)` pairs with only a single connection. 
